# Generated by Django 5.0.10 on 2025-01-04 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_consultorio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de consultorio')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id_datos', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de datos')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono_movil', models.IntegerField(verbose_name='Teléfono móvil')),
                ('telefono_fijo', models.IntegerField(verbose_name='Teléfono fijo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_registro', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Información de usuario',
                'verbose_name_plural': 'Información de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dominilio', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del domicilio')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero_exterior', models.IntegerField(verbose_name='Número exterior')),
                ('numero_interior', models.CharField(max_length=10, verbose_name='Número interior')),
                ('colonia', models.CharField(max_length=20, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=25, verbose_name='Municipio')),
                ('codigo_postal', models.IntegerField(verbose_name='Código postal')),
                ('pais', models.CharField(max_length=15, verbose_name='País')),
                ('entidad_federativa', models.CharField(max_length=20, verbose_name='Entidad federativa')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de especialidad')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la especialidad')),
                ('especialidad_descripcion', models.CharField(max_length=140, verbose_name='Descripción de la especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de horario')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de término')),
                ('turno', models.CharField(max_length=10, verbose_name='Turno')),
                ('dias_trabaja', models.JSONField(blank=True, default=list, null=True, verbose_name='Días que trabaja')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
