# Generated by Django 5.0.10 on 2025-01-04 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='id_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Cédula de doctor asignado'),
        ),
        migrations.AddField(
            model_name='datos',
            name='id_domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.direccion', verbose_name='Domicilio relacionado'),
        ),
    ]
