# Generated by Django 5.0.10 on 2025-01-04 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del usuario')),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('rol_descripcion', models.CharField(max_length=140, verbose_name='Descripción del rol')),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del paciente')),
                ('id_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.datos', verbose_name='Datos del paciente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipousuario', verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('dni_trabajador', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='DNI del trabajador')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('id_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.datos', verbose_name='Datos del trabajador')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipousuario', verbose_name='Tipo de usuario')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trabajador', verbose_name='DNI del trabajador')),
            ],
            options={
                'verbose_name': 'Recepcionista',
                'verbose_name_plural': 'Recepcionistas',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula profesional')),
                ('estado', models.BooleanField(blank=True, default=False, verbose_name='Disponible')),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.especialidad', verbose_name='Especialidad')),
                ('dni_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trabajador', verbose_name='Trabajador relacionado')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
    ]
