# Generated by Django 5.0.10 on 2025-01-04 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del medicamento')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del medicamento')),
                ('tipo_medicamento', models.CharField(max_length=20, verbose_name='Tipo de medicamento')),
                ('medicamento_descripcion', models.CharField(max_length=200, verbose_name='Descripción del medicamento')),
                ('precio_medicamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del medicamento')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha del pago')),
                ('hora_pago', models.TimeField(verbose_name='Hora del pago')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del pago')),
                ('estatus_pago', models.BooleanField(default=False, verbose_name='Estatus del pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la receta')),
                ('estatus', models.BooleanField(default=False, verbose_name='Estatus de la receta')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Tipo de servicio')),
                ('nombre_servicio', models.CharField(max_length=25, verbose_name='Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la cita')),
                ('estatus', models.BooleanField(default=False, verbose_name='Estatus de la cita')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Doctor')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del inventario')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad en Inventario')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.medicamento', verbose_name='Nombre del medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del diagnóstico')),
                ('diagnostico_descripcion', models.CharField(max_length=500, verbose_name='Descripción del diagnóstico')),
                ('id_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Doctor')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del tratamiento')),
                ('tratamiento_descripcion', models.CharField(max_length=500, verbose_name='Descripción del tratamiento')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.medicamento', verbose_name='Medicamento')),
                ('id_receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='id_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.tratamiento', verbose_name='Tratamiento'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de venta')),
                ('Fecha_venta', models.DateField(verbose_name='Fecha de la venta')),
                ('hora_venta', models.TimeField(verbose_name='Hora de la venta')),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.medicamento', verbose_name='ID del medicamento')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.servicio', verbose_name='ID del servicio')),
            ],
        ),
    ]
